### PR TITLE
@devoinc scope & GitHub Actions

### PR DESCRIPTION
**Pull request by apbarrero**

### CODE REVIEW

**Comment by tripu** [comment]
LGTM.

Are we taking care of [`npm deprecate`](https://docs.npmjs.com/cli/v8/commands/npm-deprecate)-ing all versions with the previous scope `@devo` when the new one is published for the first time, too? I think we should add a message pointing to the new name of the package.

**Review by Worvast — APPROVED** [review]
Ok a todo. ¿Lo puedes mergear tu?

**Comment by Worvast** [comment]
> 

yeah we want to deprecate all versions. js-helper for example is deprecated now:

https://www.npmjs.com/package/@devo/js-helper

**Comment by apbarrero** [comment]
FYI @tufosa :point_up:

**Pull request merged**
